export const getPaginationClasses = (
  currentIndex: number,
  position: number
): string => {
  const classesMap = [
    [
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
    ],
    [
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
    ],
    [
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
    ],
    [
      'hidden',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
    ],
    [
      'hidden',
      'hidden',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'hidden',
      'hidden',
      'hidden',
    ],
    [
      'hidden',
      'hidden',
      'hidden',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'hidden',
      'hidden',
    ],
    [
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'hidden',
    ],
    [
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
    ],
    [
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
      'w-2 h-2 bg-white/25 rounded-full',
    ],
    [
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'hidden',
      'w-1.5 h-1.5 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-2 h-2 bg-white/25 rounded-full',
      'w-4 h-2 bg-white rounded-lg',
    ],
  ];

  return classesMap[currentIndex][position];
};
